version: '3'

services:
    web:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./web:/var/www/html
            - ./docker/site.conf:/etc/nginx/conf.d/default.conf
        networks:
            - web
    php:
        build: ./docker/
        volumes:
            - ./web:/var/www/html
        networks:
            - web

networks:
    web:
        driver: bridge
